[package]
name = "phichain-compiler"
version = "1.0.0-beta.2"
edition = "2021"

[dependencies]
phichain-chart = { path = "../phichain-chart" }
num = "0.4.3"
anyhow = "1.0.89"
thiserror = "2.0.12"
itertools = "0.14.0"
nalgebra = "0.33.1"
